version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    command: air
    volumes:
      - ./server:/app
    environment:
      # This single URL is used for both the GitHub callback and the final redirect.
      # Nginx will route requests correctly based on the path.
      - FRONTEND_URL=http://localhost:8088
    restart: always
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8080"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8088
    restart: always
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:7734"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "8088:80"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy
    restart: always 