version: '3.8'

services:
  backend:
    build:
      context: ./server
    environment:
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
    restart: always

  frontend:
    build:
      context: ./client
      args:
        VITE_API_URL: ${API_URL}
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always