FROM golang:1.24-alpine

# Install netcat for healthchecks and air for hot-reloading
RUN apk add --no-cache netcat-openbsd && go install github.com/air-verse/air@latest

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

# Copy the air config file
COPY .air.toml .

# Copy the rest of the source code
COPY . .

CMD ["air"] 